---
- name: "Update packages"
  command: "yum update -y"

- name: "Install basic packages"
  yum:
    name={{ item }}
    state=present
  with_items:
      - nmap
      - telnet
      - vim
      - expect
      - net-tools
      - git