servers=[
  {
    :vm_hostname => "node-0",
    :vm_box => "juliojmphjv/debian11",
    :vm_cpus => 2,
    :vm_mem => 2048,
  },
  {
    :vm_hostname => "node-1",
    :vm_box => "juliojmphjv/debian11",
    :vm_cpus => 2,
    :vm_mem => 2048,
  },
  {
    :vm_hostname => "node-2",
    :vm_box => "juliojmphjv/debian11",
    :vm_cpus => 2,
    :vm_mem => 2048,
  }
]

Vagrant.configure("2") do |config|

  servers.each do |srv|

    config.vm.define srv[:vm_hostname] do |node|

      node.vm.box = srv[:vm_box]
      node.vm.hostname = srv[:vm_hostname]
      
      node.vm.provider :libvirt do |kvm|
        kvm.cpus = srv[:vm_cpus]
        kvm.memory = srv[:vm_mem]
      end

      # node.vm.synced_folder "./project_files", "/vagrant", disabled: false
    end
    
    config.vm.box_check_update = false
    config.ssh.insert_key = false
    config.ssh.private_key_path = ["~/.ssh/vagrant/id_rsa"]
    config.vm.post_up_message = "Welcome to Vagrant with Qemu"
  
  end
end
